name: game2048_workflow
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        java-version: [8, 11, 14]
  
    steps: 
    - name: Checkout project
      uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: Compile project
      run: mvn package
