name: game2048_workflow
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux]
  
    steps: 
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 14                    
        server-id: github  
    - name: Compile project
      run: mvn package --file pom.xml
