name: game2048_workflow
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux]
 
    steps: 
    - name: Checkout project
      uses: actions/checkout@v2

    - name: Compile project
      run: mvn compile
  
  test:
    runs-on: [self-hosted, linux]
    needs: [build]
    
    steps:    
      - name: Make Unit-Tests
        run: mvn test

  package:
    runs-on: [self-hosted, linux]
    needs: [build, test]
    
    steps:
      - name: Create Package
        run: mvn package
        
  deploy:
    runs-on: [self-hosted, linux]
    needs: [build, test, package]
    
    steps:
      - run: docker ps
        
      - run: docker image rm --force game2048
      - run: run --rm -d --name tomcat -p 8080:8080 game2048
